version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build: # This is the name of the job, feel free to change it to better match what you're trying to do!
    docker:
      - image: cimg/python:3.10.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          name: Restore pipenv dependency cache
          keys:
            - pipenv-deps-{{ checksum "Pipfile.lock" }}
      - python/install-packages:
          args: --dev --deploy --ignore-pipfile
          pkg-manager: pipenv
          cache-version: v3
          venv-cache: false
      - save_cache:
          name: Save pipenv dependency cache
          paths:
            - /home/circleci/project/.venv
          key: pipenv-deps-{{ checksum "Pipfile.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test: # This is the name of the job, feel free to change it to better match what you're trying to do!
    docker:
      - image: cimg/python:3.10.2
    parallelism: 1
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: |
            pipenv run pytest -k test_ --junitxml=test-results/junit/junit.xml --html=test-results/html/report.html | circleci tests split --split-by=timings
      - store_artifacts:
          path: test-results 
      - store_test_results:
          path: test-results

workflows:
  build-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build
      - test:
          requires:
            - build
